import { Members, ProfMembers } from "@/types/members";

export const professionalMembers: ProfMembers[] = [
  {
    id: 1,
    name: "Dr. Sai Prakash Leomuthu",
    desig: "Chairman & CEO",
    desig2: "Sairam Institutions",
    linkedin: "https://www.linkedin.com/in/sairamceo/",
    mailid: "ceo@sairamgroup.in",
    image: "/images/members/professional/ceo.png",
  },
  {
    id: 2,
    name: "Dr. Raja J",
    desig: "Principal",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://in.linkedin.com/in/raja-j-32b44164",
    mailid: "principal@sairam.edu.in",
    image: "/images/members/professional/rajaj.jpg",
  },
  {
    id: 3,
    name: "Dr. Palanikumar K",
    desig: "Principal",
    desig2: "Sri Sairam Institute of Technology",
    linkedin: "https://in.linkedin.com/in/dr-palanikumar-k-5ba50827",
    mailid: "principal@sairamit.edu.in",
    image: "/images/members/professional/palanikumark.jpg",
  },{
    id: 4,
    name: "Dr. Soma Prathibha",
    desig: "Faculty Advisor",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://www.linkedin.com/in/dr-soma-prathibha-a7884167/",
    mailid: "prathibha.IT@sairam.edu.in",
    image: "/images/members/professional/soma-mam.webp",
  },
  {
    id: 11,
    name: "Dr. Azhagumurugan R",
    desig: "Professor, Department of EEE",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://in.linkedin.com/in/dr-azhagumurugan-r-b80a374a",
    mailid: "azhagumurugan@ieee.org",
    image: "/images/members/professional/azhagumurugan.jpeg",
  },
  {
    id: 8,
    name: "Dr. Brindha Devi V",
    desig: "Professor, Department of IT",
    desig2: "Sri Sairam Institute of Technology",
    linkedin: "https://in.linkedin.com/in/dr-v-brindha-devi-28ba80194",
    mailid: "hodit@sairamit.edu.in",
    image: "/images/members/professional/brindhadeviv.jpg",
  },
  {
    id: 9,
    name: "Dr. Meenakshi B",
    desig: "Professor, Department of EEE",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://in.linkedin.com/in/meenakshi-balasubramanian-bb430824",
    mailid: "Meenakshi.EEE@sairam.edu.inv" +
      "",
    image: "/images/members/professional/meenakshib.jpg",
  },
  {
    id: 6,
    name: "Dr. Porselvi T",
    desig: "Professor, Department of EEE",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://www.linkedin.com/in/porselvit",
    mailid: "Porselvi.EEE@sairam.edu.in",
    image: "/images/members/professional/porselvi.png",
  },
  {
    id: 7,
    name: "Dr. Sankari S",
    desig: "Professor, Department of IT",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://in.linkedin.com/in/dr-sankari-s-a9b822154",
    mailid: "Sankari.IT@sairam.edu.in",
    image: "/images/members/professional/sankaris.jpg",
  },
  {
    id: 5,
    name: "Dr. Puthilibai G",
    desig: "Professor, Department of Chemistry",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://in.linkedin.com/in/dr-g-puthilibai-70725545",
    mailid: "puthilibai.che@sairam.edu.in",
    image: "/images/members/professional/puthilibaig.jpg",
  },
  {
    id: 10,
    name: "Mr. Mohanraj K",
    desig: "Assistant Professor, Department of EIE",
    desig2: "Sri Sairam Engineering College",
    linkedin: "https://in.linkedin.com/in/mohan-raj-a292551aa",
    mailid: "mohanraj.ice@sairam.edu.in",
    image: "/images/members/professional/mohanraj.jpg",
  },

];



export const studentMembers: Members[] = [
  {
    id: 1,
    name: "Dineshkumar S",
    designation: "President",
    linkedin: "https://www.linkedin.com/in/dineshkumar-sankar-81761a205/",
    mailid: "dineshkumar.s@ieee.org",
    image: "/images/members/23/Dineshkumar_Sankar.jpg",
    //
  },
  {
    id: 2,
    name: "Anushree U",
    designation: "Vice President",
    linkedin: "https://www.linkedin.com/inushree-udhayakumar-088797204/",
    mailid: "anushree.udhayakumar@ieee.org",
    image: "/images/members/23/Anushree.png",
    //
  },
  {
    id: 3,
    name: "Gnana Padmesh M K",
    designation: "Treasurer",
    linkedin: "https://www.linkedin.com/in/gnana-padmesh-c-k-2002/",
    mailid: "gnanapadmesh.ck@ieee.org ",
    image: "/images/members/23/Gnana_Padmesh.jpg",
  },
  {
    id: 4,
    name: "Tapasya K",
    designation: "Corresponding Scretary",
    linkedin: "https://www.linkedin.com/in/tapasya-k/",
    mailid: "tapasyak@ieee.org",
    image: "/images/members/23/tapasya_k.jpg",
  },
  {
    id: 5,
    name: "Kishore M A",
    designation: "Recording Secretary",
    linkedin: "https://www.linkedin.com/in/kishore2003/",
    mailid: "kishorema@ieee.org",
    image: "/images/members/23/Kishore.png",
  },
  {
    id: 6,
    name: "Raghul D",
    designation: "Volunteer Director",
    linkedin: "HKN Member",
    mailid: "raghul.dayanithi@ieee.org",
    image: "/images/members/23/Raghul_d.jpg",
  },
  {
    id: 7,
    name: "Solaiganesh S",
    designation: "Event Director",
    linkedin: "https://www.linkedin.com/in/solaiganesh-s-47379b239/",
    mailid: "solaiganesh@ieee.org",
    image: "/images/members/23/solaiganesh.jpg",
  },
  {
    id: 8,
    name: "Jai Akash S",
    designation: "Public Relations Director",
    linkedin: "https://www.linkedin.com/in/jai-akash-s-017289224/",
    mailid: "jaiakash@ieee.org",
    image: "/images/members/23/Jaiakash.jpg",
  },
  {
    id: 9,
    name: "Suvigshaa S",
    designation: "Recruitment Director",
    linkedin: "https://www.linkedin.com/in/s-suvigshaa-b47177229/",
    mailid: "ssuvigshaa@ieee.org",
    image: "/images/members/23/Suvigshaa.jpg",
  },
  {
    id: 10,
    name: "Yashwanth J",
    designation: "Operational Director",
    linkedin: "https://www.linkedin.com/in/yashwanth-j-118678226/",
    mailid: "yashwanthj@ieee.org",
    image: "/images/members/23/Yashwanth_J.jpg",
  },
  {
    id: 11,
    name: "Venkatapathi K",
    designation: "Webmaster",
    linkedin: "HKN Member",
    mailid: "Venkatapathi@ieee.org",
    image: "/images/members/23/Venkatapathi_K.png",
  },
  {
    id: 12,
    name: "Vignesh Velappan",
    designation: "HKN Member",
    linkedin:
      "https://www.linkedin.com/in/vignesh-velappan-%F0%9F%87%AE%F0%9F%87%B3-237730250",
    mailid: "vigneshvelappan30@gmail.com",
    image: "/images/members/24/vigneshvelappan.jpg",
  },
  {
    id: 13,
    name: "Rahul V",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/rahulvijayanand",
    mailid: "rahulvijayanand@ieee.org",
    image: "/images/members/24/rahulv.png",
  },

  {
    id: 14,
    name: "Sai Sakthivel Rajamani Surendran",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/saisakthivel2k3/",
    mailid: "saisakthivel2k3@ieee.org",
    image: "/images/members/24/saisakthivel.jpg",
  },
  {
    id: 15,
    name: "Gowtham P N",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/gowtham-naren-417664257/",
    mailid: "gowthamnaren2017@gmail.com",
    image: "/images/members/24/gowtham.png",
  },
  {
    id: 16,
    name: "Nasreen Begam Z",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/z-nasreen-begam-015495257",
    mailid: "nasreenbegam14@ieee.org",
    image: "/images/members/24/nasreenbegam.png",
  },
  {
    id: 17,
    name: "Ruthi Shankari",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/ruthi-shankari/",
    mailid: "sitarandtsukki@gmail.com",
    image: "/images/members/24/ruthishankari.jpg",
  },
  {
    id: 18,
    name: "Jagadeesh G",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/jagadeesh-gopalakrishnan-367a47253/",
    mailid: "jagadeeshgopalakrishnan@ieee.org",
    image: "/images/members/24/jagadeesh.jpg",
  },
  {
    id: 19,
    name: "Thrisala K",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/thrisala-k-b00437257",
    mailid: "thrisala167@gmail.com",
    image: "/images/members/24/thrisala.png",
  },
  {
    id: 20,
    name: "Tharushi S S",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/tharushi-s-s/",
    mailid: "tharushibabu@ieee.org",
    image: "/images/members/24/tharushi.jpg",
  },
  {
    id: 21,
    name: "Savitha N",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/savitha-narayanamoorthy-7695a7254/",
    mailid: "savithanarayanamoorthy@ieee.org",
    image: "/images/members/24/savitha.jpg",
  },
  {
    id: 22,
    name: "Harish V P",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/vpharish/",
    mailid: "harishvp2004@gmail.com",
    image: "/images/members/24/harishvp.png",
  },
  {
    id: 23,
    name: "Pranjna B",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/pranjna-b-114627258",
    mailid: "pranj.jaya16@gmail.com",
    image: "/images/members/24/pranjna.jpg",
  },

  {
    id: 24,
    name: "Sandhiya A",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/sandhiya-arulmurugan-2b10a7258",
    mailid: "sandhiya042005@gmail.com",
    image: "/images/members/24/sandhiyaa.jpg",
  },
  {
    id: 25,
    name: "Sanjay",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/sanjaykumar-s-b30062296/",
    mailid: "sanjaykumar04@ieee.org",
    image: "/images/members/24/sanjay.jpg",
  },
  {
    id: 26,
    name: "Shreeja S",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/shreeja-s-1b17a925a",
    mailid: "shreeja1318@gmail.com",
    image: "/images/members/24/shreeja.jpg",
  },
  {
    id: 27,
    name: "Mahalakshmi",
    designation: "HKN Member",
    linkedin: "https://www.linkedin.com/in/mahalakshmi-sundararajan-645602218",
    mailid: "Mahalakshmi.S@ieee.org",
    image: "/images/members/24/mahalakshmi.jpg",
  },
];
